- name: Deploy to Tomcat
  hosts: web
  become: yes

tasks:
  tasks:
    - name: Copy WAR file to Tomcat
      copy:
        src: "/home/unified/.m2/repository/com/example/mavansi/1.0-SNAPSHOT/mavansi-1.0-SNAPSHOT.war"
        dest: "/opt/tomcat/webapps/mavansi.war"
        remote_src: no

  - name: Restart Tomcat
    service:
      name: tomcat
      state: restarted
